### ISSUE TITLE
System.IO.FileNotFoundException: The device is not ready (0x80070015)

### ISSUE THREAD

**Issue by Aytackydln** [DubyaDude/WindowsMediaController#11]
This error comes up on some of Aurora's users. Sadly this stack trace is all I can get.

![image](https://user-images.githubusercontent.com/11393706/205510683-3ee2488e-0e75-4e00-ace3-19e65c2731c8.png)
![image](https://user-images.githubusercontent.com/11393706/205510688-f58e9678-e434-4e03-b0fa-fcee533b70f8.png)

**Comment by DubyaDude** [comment]
Hmmm, odd, I wonder if the recent switch to force OnSongChange to run synchronously caused this.
Did this issue only start occurring with the recent updates?

**Comment by Aytackydln** [comment]
Yes, started with 2.3.2

**Comment by DubyaDude** [comment]
My apologies, this week has been a bit hectic.
Does this happen consistently or sporadically?
Might be worth it to try version 2.3.1 just to confirm that is the issue so I can roll that specific change back.

**Comment by Aytackydln** [comment]
I actually didn't hear anything else from the users. Also no more people are reporting it

**Comment by DubyaDude** [comment]
I've decided to undo the change anyways in the 2.4.0 release.
Will be closing since I'm very certain that was the issue; if the issue still exists in this release, please re-open.

**Comment by DubyaDude** [comment]
This issue should now be generally handled in https://github.com/DubyaDude/WindowsMediaController/releases/tag/2.5.0
