### ISSUE TITLE
RPC_E_CALL_CANCELED when mediaManager Start or StartAsync

### ISSUE THREAD

**Issue by KRtekTM** [DubyaDude/WindowsMediaController#15]
Hello,

I'm getting this error when trying to call Start or StartAsync on MediaManager.
System.Exception: 'Call was canceled by the message filter. (Exception from HRESULT: 0x80010002 (RPC_E_CALL_CANCELED))'

Once I was able to trigger everything right however since then every run of my app crashes with this exception. Try/Catch is not solution as it crashes every single time.

Did you experienced the same issue? Thanks a lot!

**Comment by KRtekTM** [comment]
Restart of Windows helped. Probably I reached the limit of RPC calls to the system.

**Comment by DubyaDude** [comment]
Yep, most likely just a Windows moment. Constant runs of the app might cause it, though information on that error is relatively sparse. Calling `MediaManager.Dispose` on the application exit (EX: [AppDomain.CurrentDomain.ProcessExit](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?view=net-6.0)) could help reduce the chances of running into this.
