### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by LAB02-Admin** [DubyaDude/WindowsMediaController#4]
Hey @DubyaDude,

This is a great library, however, using it on .NET 6 gives the following error:

```
WindowsMediaController.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher. 
An updated version of the component supporting .NET 5 is needed. For more information, see https://aka.ms/netsdk1149
```

Do you think it would be possible to achieve this functionality without WinRT?

Thanks!

**Comment by DubyaDude** [comment]
Yes, I did notice this when testing, however, haven't had time to quite dig into it. Taking a quick look at it there does seem the be a 'replacement' way to do this for NET5+, but to be frank it's quite jank:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/interop/5.0/built-in-support-for-winrt-removed#recommended-action

I'll look into making a port for NET6, not sure how free I'll be for some time.

**Comment by LAB02-Admin** [comment]
Update: it seems that by just using `Windows.Media.Control`, a lot is still possible. Quick 'n crude code:

```C#
var sessionManager = await GlobalSystemMediaTransportControlsSessionManager.RequestAsync();
var sessions = sessionManager.GetSessions();

foreach (var session in sessions)
{
    var mediaProperties = await session.TryGetMediaPropertiesAsync();

    Log.Information("Session state: {state}", session.GetPlaybackInfo().PlaybackStatus);
    Log.Information("{artis} - {title}", mediaProperties.Artist, mediaProperties.Title);
}
```

**Comment by LAB02-Admin** [comment]
Thanks for the fast response! Take your time, this should be ok for now :)

**Comment by DubyaDude** [comment]
Good to hear, I'll keep this open until I get it out to the NuGet package

**Comment by DubyaDude** [comment]
NET5/NET6 support added in [2.2.0](https://github.com/DubyaDude/WindowsMediaController/releases/tag/2.2.0)

And added documentation of hurdles some may face [here](https://github.com/DubyaDude/WindowsMediaController#net-5)

**Comment by LAB02-Admin** [comment]
Impressively fast, thanks @DubyaDude!
