### ISSUE TITLE
MediaMuted Information (if possible)

### ISSUE THREAD

**Issue by Aytackydln** [DubyaDude/WindowsMediaController#5]
Hello, I'm the current maintainer of Aurora-RGB and also making a plugin for Artemis-RGB. I will also reference this repository on those projects.
https://github.com/Aurora-RGB/Aurora
https://github.com/Aytackydln/Artemis.MediaInfo
https://github.com/Artemis-RGB/Artemis

Thanks for the library, RGB devices will be able to react depending on media :)

I wanted to add media muted information too but library didn't expose that. I also noticed playback information updates whenever I mute/unmute media so I thought it would be possible to add to this library.

**Comment by DubyaDude** [comment]
> I also noticed playback information updates whenever I mute/unmute media so I thought it would be possible to add to this library.

What media player showed off this behavior?

**Comment by Aytackydln** [comment]
That was Opera GX, I believe chromium browsers do that

**Comment by DubyaDude** [comment]
Could not reproduce with Chrome + Spotify and Chrome + Youtube.
It's very well possible that either the browser/site you used changes state when muted for efficiency purposes, though this is just my educated guess.

Upon further poking around, there is no volume field included in Microsofts "[GlobalSystemMediaTransportControlsSession](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssession)" system which is what the wrapper is currently for.

If there's documentation I missed, please let me know. But in terms of grabbing volume data, this wrapper would need to be used in tandem with a tool that grabs per-app volume data (like [NAudio](https://github.com/naudio/NAudio)).

**Comment by Aytackydln** [comment]
Alright, thanks for looking into it. Aurora already uses NAudio, people can use that then.
