### ISSUE TITLE
Add/Change Windows targets to Windows 10

### ISSUE THREAD

**Issue by Aytackydln** [DubyaDude/WindowsMediaController#9]
Current windows targets (windows10.0.22000.0) are for windows 11, minimum windows 10 target is windows10.0.17763.0
Because of this I have to build my own dll for the plugin I'm using for Artemis (it uses windows10.0.17763.0 dlls)

Target framework versioning is confusing, yes. I also made this mistake thinking I was targeting my plugin for w10 but it was actually w11

**Comment by DubyaDude** [comment]
Added in 2.3.1 release.
Nuget is still processing the update as I type this: https://www.nuget.org/packages/Dubya.WindowsMediaController/2.3.1
